<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PassThrough.Broker</RootNamespace>
    <AssemblyName>PassThrough.Broker</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PassThrough.Core\PassThrough.Core.csproj" />
  </ItemGroup>

</Project>
